name: RATP
description: UI themed for RATP.

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/map.png
    - assets/ratp.png

  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/Cabin-Regular.ttf
        - asset: fonts/Cabin-Bold.ttf
          weight: 600
